### PR TITLE
VP-73 uses ant design styles/components where possible

### PR DESCRIPTION
**Pull request by annebilek**

### CODE REVIEW

**Review by avowkind — COMMENTED** [review]
Menu is not using <FormattedMessage> and bypasses internationalisation.
see https://voluntarily.atlassian.net/wiki/spaces/VP/pages/4423681/Voluntari.ly+is+Multilingual
navigation.json key can be used to set the react-intl key

I get a run time error starting the page. ReferenceError: window is not defined
    at Navigation (/Users/watkinsav/workspace/voluntarily/vly1/client/modules/App/components/Header/Navigation.js:7:22)

This may be because the application is isomorphic and pages are being rendered on the server. If this is the problem then the menu highlight should be attached to a relevant react state such as the Route.

**Comment by avowkind** [comment]
Thanks for doing that. There will be some work to do on the Activity and Opportunity cards as they no longer appear to be using rows. But that can be a different ticket.

**Comment by annebilek** [comment]
> Menu is not using and bypasses internationalisation.
> see https://voluntarily.atlassian.net/wiki/spaces/VP/pages/4423681/Voluntari.ly+is+Multilingual
> navigation.json key can be used to set the react-intl key
> 
> I get a run time error starting the page. ReferenceError: window is not defined
> at Navigation (/Users/watkinsav/workspace/voluntarily/vly1/client/modules/App/components/Header/Navigation.js:7:22)
> 
> This may be because the application is isomorphic and pages are being rendered on the server. If this is the problem then the menu highlight should be attached to a relevant react state such as the Route.

Thanks for the review, @avowkind . I've pushed a fix for the window issue, using the location object provided by react-router.

Regarding localisation, Ant Design comes with localisation support https://2x.ant.design/docs/react/i18n. Did you want me to address this in this PR or are you ok with a separate PR.

Would be a good opportunity to discuss PR philosophy. I am a fan of trunk based development and short lived PRs addressing single concerns, other folks like longer branches tied to an issue/story that won't be merged until all the requirements are fulfilled. Is there a particular approach you'd like to encourage?

**Comment by avowkind** [comment]
Hi Anne

Thanks for the PR I’ve merged it to master.

For i18N we are using react-intl. Which has everything required.  I’ve updated some docs to https://voluntarily.atlassian.net/wiki/spaces/VP/pages/6324227/Managing+Translations <https://voluntarily.atlassian.net/wiki/spaces/VP/pages/6324227/Managing+Translations>

I’m about to check in a branch that implements the above.

We will support English and Te rem Māori from the start - both in titles/menus etc but also in body content pages. 
As a project we hope will go global its easier to get it all in place early than try to retrofit. 

Antd localisation should just use react-Intl. 

A>

**Pull request merged**
